### ISSUE TITLE
Adding a property to an entity

### ISSUE THREAD

**Issue by mycroftcanner** [mjibson/goon#101]
Is it safe to add a property to an entity? or should I migrate my data first?

**Comment by xStrom** [comment]
Yes it is safe. If you add a property to an entity and then load data from the datastore that doesn't have that property, then the property will have its zero value. Saving always overwrites, so there are no surprises there.

It is also safe to remove a property. When loading from the datastore, the property is just ignored. When saving, then once again it overwrites the data in the datastore, so that it won't have the property there either.

What's dangerous is changing the data type of a property, say from `float64` to `int64`. I have not tested it, but wouldn't be surprised if it can cause errors or even crashes.
