### ISSUE TITLE
Add support for google.golang.org/appengine packages

### ISSUE THREAD

**Issue by garyburd** [mjibson/goon#49]
Add support for applications that use the  [google.golang.org/appengine](http://godoc.org/google.golang.org/appengine) packages. These packages work on App Engine Classic and managed VMs. 

There are a couple of ways to do this. One is to fork Goon and replace all uses of appengine/* with google.golang.org/appengine/* and appengine.Context with the [x/net Context](http://godoc.org/golang.org/x/net/context#Context). A second option is to write a shim layer above Goon.

**Comment by garyburd** [comment]
The appengine/aetest package is not ported to google.golang.org/appengine. The shim looks like the best option for now.

**Comment by mjibson** [comment]
I tried porting goon to the golang.org/appengine package last night and aetest is where I got stuck. I'd like to try a little harder to see if I can fake the context enough to work, but I agree that the shim is probably the best option.

**Comment by riannucci** [comment]
@garyburd how did you end up shimming goon? Did it work out?

Short of [this issue][1] being fixed, I'm thinking of doing a quick fork+convert of goon (minus tests), just to have the option. It really sucks that aetest doesn't work in the new SDK yet :(. Anyway, just thought I'd post here as an FYI.

[1]: https://code.google.com/p/googleappengine/issues/detail?id=11685

**Comment by garyburd** [comment]
@riannucci I stayed with the App Engine classic APIs.

**Comment by zboralski** [comment]
Any progress on this issue?

**Comment by mjibson** [comment]
Nope. I got it working but without the aetest stuff, which is a lot. I'll try again and see if I can ignore that issue.

**Comment by riannucci** [comment]
would it be possible to have a set of files defining goon.Context to be either appengine.Context or "golang.org/x/net/context".Context? Then depending on if `-tags appengine` were specified, FromContext would accept one or the other, but internally goon would be using goon.Context? I think it might work, since both goon.Context and appengine.Context are interfaces so they should auto-cast without having to name the underlying type at the callsites.

It may be necessary to wrap some functions though, since stuff like PropertyLoaderSaver have changed to use []Property instead of chan Property though. not sure.

The benefit, of course, would be that the tests would still be runnable under `goapp`. Maybe?

**Comment by riannucci** [comment]
(FWIW, it appears that this is the way the new SDK supports old-appengine too; it has some dual implementations around whichever Context type it's using, depending on the appengine build tag).

https://github.com/golang/appengine/blob/master/internal/api_classic.go
https://github.com/golang/appengine/blob/master/internal/api.go

**Comment by zboralski** [comment]
[Apparently](https://github.com/golang/oauth2) "If you don't want to update your entire app to use the new App Engine packages, you may use both sets of packages in parallel..."

**Comment by riannucci** [comment]
Only if you don't use managed VMs :). I don't think you can use the original SDK on the new managed VMs at all. The new SDK (sort of) supports both, but there are some non-trivial incompatibilities, like *newsdk.datastore.Key and *oldsdk.datastore.Key are not fungible, so you can't mix and match a given subpackage of the SDK.

**Comment by ceram1** [comment]
Possible way: (to use both, in classic app enigine app)
[golang/oauth2](https://github.com/golang/oauth2#app-engine)

**Comment by mjibson** [comment]
I spoke to David Symonds at GopherCon. He said porting aetest is likely to happen in the next few weeks. This will enable the easy solution to this issue.

**Comment by kidoman** [comment]
I wonder if we could use this in the interim: https://github.com/qedus/nds/blob/master/nds_test.go#L24-L37

We are heavily invested into Goon and had to convert to the new appengine packages due to other libraries all requiring the new context.

**Comment by quasor** [comment]
this just happened: https://github.com/golang/appengine/commit/b938f229d68c84e923540320f32152e0955badb9

**Comment by mjibson** [comment]
Fantastic. I hope to finish this up soon then.

**Comment by EVILoptimist** [comment]
OMG YES
https://godoc.org/google.golang.org/appengine/aetest

**Comment by mzimmerman** [comment]
I've started work on this here -- https://github.com/mzimmerman/goon/commit/82063655956c909aa5bedf0d84bd815011c8726b -- in theory it's functional but my goon tests weren't passing before I started work on it (and they're not passing now either)  Some underlying python error it seems but I haven't had enough time to look into it.

Working on porting one of my private apps to use this version of goon because it has an extensive test suite.

**Comment by mjibson** [comment]
For those playing along at home, try out: https://github.com/mjibson/goon/pull/51
